package com.utilitybox.app.tools.calculate

/**
 * A 1024-word list for passphrases. The count is an exact power of two so each
 * word chosen uniformly at random contributes exactly 10 bits of entropy,
 * which keeps the strength estimate honest. Words are short, common and
 * unambiguous to type.
 */
internal object PassphraseWords {
    val words: List<String> = listOf(
        "able", "acid", "acorn", "actor", "adapt", "admit", "adobe", "adult",
        "again", "agent", "agree", "ahead", "alarm", "album", "alert", "alien",
        "alike", "alive", "alley", "alloy", "alone", "amber", "amble", "amend",
        "amuse", "angel", "anger", "angle", "ankle", "apple", "apron", "arena",
        "argue", "arise", "armor", "aroma", "arrow", "ashes", "aside", "asset",
        "atlas", "attic", "audio", "avoid", "awake", "award", "aware", "bacon",
        "badge", "badly", "baker", "balmy", "banjo", "barge", "basil", "basin",
        "basket", "batch", "beach", "beacon", "beam", "bean", "beard", "beast",
        "bench", "berry", "bicycle", "birch", "bison", "black", "blade", "blaze",
        "blend", "bliss", "block", "bloom", "blues", "bluff", "blunt", "board",
        "bonus", "boost", "booth", "borrow", "bottle", "boulder", "bounce", "bracket",
        "braid", "brain", "brave", "bread", "break", "breeze", "brick", "bridge",
        "brief", "bright", "bring", "brisk", "broad", "bronze", "brook", "broom",
        "brush", "bubble", "bucket", "buddy", "budget", "buffet", "bugle", "build",
        "bulk", "bunch", "bundle", "bunny", "burst", "butler", "butter", "cabin",
        "cable", "cactus", "camel", "canal", "candle", "canoe", "canvas", "canyon",
        "carbon", "cargo", "carol", "carpet", "carrot", "carve", "castle", "catch",
        "cattle", "cause", "cedar", "cellar", "cement", "census", "chain", "chalk",
        "chance", "chapel", "charm", "chart", "chase", "cheese", "cherry", "chess",
        "chief", "chill", "chimney", "choice", "chorus", "cider", "cinema", "circle",
        "citrus", "civic", "clamp", "classic", "clever", "cliff", "climb", "clock",
        "cloth", "cloud", "clover", "cluster", "coach", "coast", "cobalt", "cocoa",
        "coffee", "collar", "colony", "column", "combine", "comet", "comfort", "comic",
        "compass", "copper", "coral", "corner", "cotton", "county", "couple", "courage",
        "cousin", "cover", "coyote", "cradle", "crane", "crater", "crayon", "cream",
        "credit", "crest", "cricket", "crimson", "crisp", "crown", "cruise", "crystal",
        "cube", "cudgel", "curious", "current", "curtain", "cushion", "custom", "cycle",
        "cypress", "daisy", "dancer", "danger", "dawn", "deal", "debate", "decade",
        "decoy", "deed", "defer", "degree", "delta", "demand", "denim", "dense",
        "depot", "desert", "design", "desk", "detail", "device", "dew", "diamond",
        "diary", "digital", "dinner", "direct", "dish", "distant", "ditch", "divide",
        "dock", "doctor", "dolphin", "domain", "donate", "donkey", "double", "dough",
        "dozen", "draft", "dragon", "drama", "drawer", "dream", "drift", "drill",
        "drink", "drive", "drone", "drum", "dryer", "duck", "dune", "dust",
        "duty", "eagle", "early", "earth", "easel", "east", "echo", "eclipse",
        "edge", "editor", "effort", "eight", "elbow", "elder", "electric", "elegant",
        "elephant", "elite", "ember", "emerald", "empire", "employ", "empty", "enable",
        "energy", "engine", "enjoy", "enough", "ensure", "entire", "entry", "equal",
        "equip", "escape", "essay", "estate", "ethics", "evening", "event", "exact",
        "excess", "exhibit", "exit", "expand", "expert", "explore", "export", "extra",
        "fabric", "facade", "factor", "fade", "faith", "falcon", "fancy", "fantasy",
        "farm", "fashion", "fault", "feast", "feather", "fence", "ferry", "festival",
        "fiber", "fiction", "field", "fierce", "figure", "filter", "final", "finch",
        "finger", "finish", "first", "fiscal", "fitness", "flag", "flame", "flavor",
        "fleet", "flint", "float", "flock", "flood", "floral", "flour", "flower",
        "fluent", "fluid", "flute", "focus", "foggy", "folder", "follow", "forest",
        "forge", "formal", "fortune", "forum", "fossil", "foster", "fountain", "fraction",
        "frame", "freedom", "freeze", "fresh", "friend", "fringe", "frost", "fruit",
        "fuel", "funnel", "future", "gadget", "galaxy", "gallery", "gallon", "garden",
        "garlic", "gather", "gauge", "gazelle", "gear", "gentle", "geyser", "giant",
        "ginger", "giraffe", "glacier", "glass", "glide", "global", "gloss", "glove",
        "glow", "golden", "gospel", "govern", "grace", "grain", "grand", "granite",
        "grape", "graph", "grasp", "gravel", "great", "green", "grid", "grill",
        "grip", "grove", "growth", "guard", "guest", "guide", "guitar", "habit",
        "hammer", "hamster", "handle", "happy", "harbor", "harvest", "hatch", "hazel",
        "header", "health", "heart", "hedge", "helmet", "herald", "herbal", "heron",
        "hidden", "hiking", "hollow", "honest", "honey", "horizon", "hornet", "horse",
        "hotel", "hunter", "hurdle", "hybrid", "hydro", "ideal", "igloo", "image",
        "impact", "import", "index", "indigo", "infant", "inform", "inject", "inner",
        "input", "insect", "inside", "insight", "instant", "invest", "invite", "iris",
        "iron", "island", "issue", "ivory", "jacket", "jaguar", "jelly", "jewel",
        "jockey", "jolly", "journal", "jungle", "junior", "jupiter", "keen", "kernel",
        "kettle", "kitten", "knight", "koala", "label", "labor", "ladder", "lagoon",
        "lantern", "laptop", "large", "laser", "latch", "laundry", "lava", "lawn",
        "layer", "leader", "leaf", "league", "leather", "lecture", "ledge", "legacy",
        "legend", "lemon", "length", "lentil", "leopard", "lesson", "letter", "level",
        "liberty", "library", "license", "lilac", "lily", "limit", "linen", "liquid",
        "listen", "little", "lively", "lizard", "llama", "lobby", "lobster", "local",
        "locker", "locust", "lodge", "logic", "lotus", "lounge", "lucky", "lumber",
        "lunar", "lunch", "lyric", "magic", "magnet", "major", "mammal", "mango",
        "manor", "mantle", "maple", "marble", "margin", "marine", "market", "marsh",
        "mask", "master", "matrix", "meadow", "measure", "medal", "medium", "melody",
        "member", "memory", "mentor", "mercy", "merit", "metal", "meteor", "method",
        "metro", "middle", "midnight", "mighty", "mild", "mimic", "mineral", "minor",
        "mint", "minute", "mirror", "mission", "mixer", "mobile", "model", "modern",
        "modest", "module", "moment", "monitor", "monkey", "month", "moral", "morning",
        "mosaic", "motion", "motor", "mountain", "mouse", "movie", "muffin", "mural",
        "museum", "music", "mustard", "mutual", "mystery", "napkin", "narrow", "nation",
        "native", "nature", "neat", "nectar", "needle", "neon", "nephew", "nerve",
        "nest", "network", "neutral", "never", "nickel", "night", "nimble", "noble",
        "noise", "nomad", "noodle", "normal", "north", "notice", "novel", "number",
        "nurse", "nutmeg", "oasis", "object", "ocean", "octave", "office", "often",
        "olive", "omega", "onion", "online", "opal", "open", "opera", "option",
        "orange", "orbit", "orchard", "order", "organ", "origin", "osprey", "otter",
        "output", "oval", "oven", "owner", "oxygen", "oyster", "pacific", "packet",
        "paddle", "pagoda", "palace", "palm", "panda", "panel", "panther", "paper",
        "parade", "parcel", "parent", "parrot", "parsley", "pastel", "pastry", "patch",
        "patio", "patrol", "pattern", "pause", "peace", "peach", "peanut", "pearl",
        "pebble", "pelican", "pencil", "people", "pepper", "perch", "perfect", "period",
        "permit", "person", "phase", "phoenix", "phone", "photo", "phrase", "piano",
        "picnic", "pigeon", "pillar", "pilot", "pine", "pioneer", "pistol", "pivot",
        "pixel", "pizza", "place", "plain", "planet", "plank", "plant", "plasma",
        "plate", "plaza", "pledge", "plenty", "plot", "plum", "plume", "pocket",
        "poem", "poet", "point", "polar", "polish", "pollen", "pond", "pony",
        "poplar", "poppy", "portal", "portion", "possum", "postal", "potato", "pottery",
        "powder", "power", "practice", "prairie", "praise", "prefer", "premium", "present",
        "press", "pretty", "price", "pride", "primary", "prince", "print", "prism",
        "prize", "probe", "produce", "profile", "project", "promise", "proof", "proper",
        "protect", "proud", "prove", "public", "pudding", "puffin", "pulse", "pumpkin",
        "punch", "pupil", "puppet", "purple", "purpose", "puzzle", "pyramid", "quail",
        "quality", "quantum", "quarry", "quartz", "queen", "quest", "quick", "quiet",
        "quilt", "quirk", "quote", "rabbit", "raccoon", "racket", "radar", "radio",
        "raft", "rail", "rain", "raisin", "rally", "ramp", "ranch", "random",
        "range", "rapid", "rare", "rate", "raven", "razor", "reach", "ready",
        "realm", "reason", "rebel", "recall", "recipe", "record", "recover", "reduce",
        "reef", "refer", "reflect", "refuge", "regard", "region", "regular", "relax",
        "relay", "relief", "remain", "remedy", "remind", "remote", "render", "rental",
        "repair", "repeat", "replace", "report", "rescue", "resist", "resort", "result",
        "retail", "retire", "return", "reveal", "review", "reward", "rhythm", "ribbon",
        "rice", "ridge", "rifle", "right", "rigid", "ripple", "rise", "ritual",
        "river", "roast", "robin", "robot", "rocket", "roller", "roof", "rookie",
        "rose", "rotate", "rough", "round", "route", "royal", "rubber", "ruby",
        "rugby", "ruler", "rumor", "runner", "rural", "sable", "saddle", "safari",
        "safety", "sage", "sail", "salad", "salmon", "salon", "salt", "sample",
        "sand", "sapphire", "satin", "sauce", "saucer", "savanna", "scale", "scarf",
        "scenic", "scheme", "school", "science", "scissor", "scope", "score", "scout",
        "screen", "script", "scroll", "sculpt", "search", "season", "second", "secret",
        "sector", "secure", "select", "senate", "senior", "sense", "sentry", "sequel",
        "serene", "series", "serve", "settle", "seven", "shade", "shadow", "shaft",
        "shallow", "shampoo", "shape", "share", "shark", "sharp", "shelf", "shell",
        "shelter", "sheriff", "shield", "shift", "shine", "shirt", "shore", "short",
        "shovel", "shower", "shrimp", "shrine", "shuttle", "sibling", "sierra", "signal",
        "silent", "silk", "silver", "simple", "singer", "siren", "sister", "sketch",
        "skill", "skirt", "sky", "slate", "sleep", "slice", "slide", "slope",
        "small", "smart", "smile", "smoke", "smooth", "snack", "snake", "sneak",
        "snow", "soccer", "social", "socket", "sodium", "solar", "solid", "solve",
        "sonar", "sonnet", "sorbet", "sound", "source", "south", "space", "spade",
        "spark", "sparrow", "speak", "speed", "spell", "sphere", "spice", "spider",
    )

    /** Bits of entropy contributed by each word. */
    const val BITS_PER_WORD = 10
}
